#!/usr/bin/env bash
# Akki - UserBot

if [ -d "resources" ]
then
    echo "Current directory Identified.."
else
    apt install git -y
    git clone https://github.com/akkityagi12/Akki
    cd Akki
fi
bash resources/startup/termux.sh
